general.import = [    "~/.config/alacritty/themes/aura.toml"]
#general.import = [ "~/.config/alacritty/themes/catppuccin-mocha.toml" ]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 4, y = 4}
opacity = 0.95
#blur = true

[colors.primary]
background = "#241f31"

[font]
size = 9.5

[font.bold]
family = "DejaVuSansM Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "DejaVuSansM Nerd Font Mono"
style = "Bold Oblique"

[font.italic]
family = "DejaVuSansM Nerd Font Mono"
style = "Oblique"

[font.normal]
family = "DejaVuSansM Nerd Font Mono"
style = "Regular"
