# taken from https://starship.rs/presets/pastel-powerline
format = """
$username\
[](bg:#4a5d46 fg:#f4d4b8)\
[](bg:#f4d4b8 fg:#4a5d46)\
$directory\
[](bg:#4a5d46 fg:#f4d4b8)\
[](bg:#f4d4b8 fg:#4a5d46)\
$git_branch\
$git_status\
[](bg:#4a5d46 fg:#f4d4b8)\
[](bg:#f4d4b8 fg:#4a5d46)\
[ ◊ ](bold bg:#f4d4b8 fg:#312320)\
[ ](fg:#f4d4b8)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#f4d4b8 fg:#312320"
style_root = "bg:#f4d4b8 fg:#312320"
format = '[ $user ](bold bg:#f4d4b8 fg:#312320)'
disabled = false

[directory]
style = "bg:#f4d4b8 fg:#312320"
format = "[ $path ](bold $style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#f4d4b8 fg:#312320"
format = '[ $symbol $branch ](bold $style)'

[git_status]
style = "bg:#f4d4b8 fg:#312320"
format = '[$all_status$ahead_behind ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#f4d4b8 fg:#312320"
format = '[ $time ]($style)'

